export const GET_ITEMS_LIST_SUCCESS  = "GET_ITEMS_LIST_SUCCESS";
export const GET_MORE_ITEMS_LIST_REQUEST = "GET_MORE_ITEMS_LIST_REQUEST";
export const GET_MORE_ITEMS_LIST_SUCCESS = "GET_MORE_ITEMS_LIST_SUCCESS";
export const GET_MORE_ITEMS_LIST_FAILURE = "GET_MORE_ITEMS_LIST_FAILURE";